AssessmentStaff/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net; 
using System.Web;
using System.Web.Mvc;
using AssessmentStaff.Models;

namespace AssessmentStaff.Controllers
{
    public class AuthController : Controller
    {
        private RootEntities db = new RootEntities();

        // GET: Auth
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string login, string password)
        {
            ViewBag.Error = "";
            if (String.IsNullOrEmpty(login) || String.IsNullOrEmpty(password))
            {
                return RedirectToAction("WrongInputData", "Errors");
            }

            var user = db.User.FirstOrDefault(a => a.Login == login && a.Password == password);
            if (user == null) 
            {
                ViewBag.Error = "Введены некорректные логин или пароль! Проверьте данные!";
            }

            return View();
        }

    }
}

AssessmentStaff/Controllers/CollabController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssessmentStaff.Models;

namespace AssessmentStaff.Controllers
{
    public class CollabController : Controller
    {
        private RootEntities db = new RootEntities();

        // GET: User
        public ActionResult Index()
        {
            var user = db.User;
            return View(user.ToList());
        }


        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Http400", "ИсключительныеСитуации");
            }
            var user = db.User.FirstOrDefault(a => a.IDUser == id);
            if (user == null)
            {
                return RedirectToAction("Http404", "ИсключительныеСитуации");
            }
            return View(user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(string login, string firstpassword, string secondpassword, string surname, string name, string patronymic, string bornDate, string roleEnum)
        {
            try
            {
                ViewBag.Error = "";
                ViewBag.ErrorDate = "";
                ViewBag.ErrorRole = "";
                ViewBag.ErrorLogin = "";
                if (String.IsNullOrEmpty(login) || String.IsNullOrEmpty(firstpassword) ||
                    String.IsNullOrEmpty(secondpassword) || String.IsNullOrEmpty(surname) ||
                    String.IsNullOrEmpty(name) || String.IsNullOrEmpty(patronymic) ||
                    String.IsNullOrEmpty(bornDate) || roleEnum == null)
                {
                    return RedirectToAction("WrongInputData", "Errors");
                }

                if (firstpassword != secondpassword)
                {
                    ViewBag.Error = "Пароли не совпадают!";
                    return View();
                }

                var newuser = db.User.FirstOrDefault(a => a.Login == login);
                if (newuser != null)
                {
                    ViewBag.ErrorLogin = "Пользователь с таким логином уже существует!";
                    return View();
                }

                int.TryParse(roleEnum, out var rEnum);
                if (rEnum != 1 && rEnum != 2 && rEnum != 3)
                {
                    ViewBag.ErrorRole = "Введена неправильная роль! 1 - Сотрудник, 2 - Администратор, 3 - Директор";
                    return View();
                }

                if (rEnum == 3)
                {
                    var newUserDirector = db.User.FirstOrDefault(a => a.Role == 3);
                    if (newUserDirector != null)
                    {
                        ViewBag.ErrorRole = "Роль директора уже занята!";
                        return View();
                    }

                }

                DateTime.TryParse(bornDate, out var Date);

                if (Date == new DateTime())
                {
                    ViewBag.ErrorDate = "Введена некорректная дата! Проверьте данные!";
                    return View();
                }

                db.User.Add(new User() { Surname = surname, Name = name, Patronymic = patronymic, BornDate = Date, Role = rEnum, Login = login, Password = firstpassword });
                db.SaveChanges();
                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("DbException", "Errors");
            }
        }
        
        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Http400", "ИсключительныеСитуации");
            }
            var user = db.User.FirstOrDefault(a => a.IDUser == id);
            if (user == null)
            {
                return RedirectToAction("Http404", "ИсключительныеСитуации");
            }

            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        

        public ActionResult Edit(string login, string surname, string name, string patronymic, string bornDate)
        {
            if (String.IsNullOrEmpty(login) || String.IsNullOrEmpty(surname) ||
                    String.IsNullOrEmpty(name) || String.IsNullOrEmpty(patronymic) ||
                    String.IsNullOrEmpty(bornDate))
            {
                return RedirectToAction("WrongInputData", "Errors");
            }

            var user = db.User.FirstOrDefault(a => a.Login == login);
            if (user == null)
            {
                return RedirectToAction("Http404", "ИсключительныеСитуации");
            }
            
            DateTime.TryParse(bornDate, out var Date);

            if (Date == new DateTime())
            {
                ViewBag.ErrorDate = "Введена некорректная дата! Проверьте данные!";
                return View();
            }

            user.Surname = surname;
            user.Name = name;
            user.Patronymic = patronymic;
            user.BornDate = Date;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Http400", "ИсключительныеСитуации");
            }

            var user = db.User.FirstOrDefault(a => a.IDUser == id);
            if (user == null)
            {
                return RedirectToAction("Http404", "ИсключительныеСитуации");
            }
            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var user = db.User.FirstOrDefault(a => a.IDUser == id);
            if (user == null)
            {
                return RedirectToAction("Http404", "ИсключительныеСитуации");
            }

            db.User.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AssessmentStaff/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – ICL</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ICL", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("О нас", "About", "Home")</li>
                    <li style="padding-left: 960px">@Html.ActionLink("Войти", "Index", "Auth")</li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AssessmentStaff/Views/Shared/_LayoutA.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – ICL</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ICL - Главная", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Сотрудники", "Index", "Collab")</li>
                    <li>@Html.ActionLink("Материалы", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Тесты", "Contact", "Home")</li>
                    <li style="padding-left: 450px">@Html.ActionLink("Личные данные", "Index", "Auth")</li>
                    <li>@Html.ActionLink("Выйти", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>